library(GarchMidas)
pdf("weights.pdf",width = 6,height = 4)
mu_result60<-fit_GarchMidas(mu,'hundredfold_return','mu',60)
mu_result48<-fit_GarchMidas(mu,'hundredfold_return','mu',48)
mu_result36<-fit_GarchMidas(mu,'hundredfold_return','mu',36)
mu_result24<-fit_GarchMidas(mu,'hundredfold_return','mu',24)
plot_weighting_scheme(mu_result60)
plot_weighting_scheme(mu_result48)
plot_weighting_scheme(mu_result36)
plot_weighting_scheme(mu_result24)

fu_result60<-fit_GarchMidas(fu,'hundredfold_return','fu',60)
fu_result48<-fit_GarchMidas(fu,'hundredfold_return','fu',48)
fu_result36<-fit_GarchMidas(fu,'hundredfold_return','fu',36)
fu_result24<-fit_GarchMidas(fu,'hundredfold_return','fu',24)
plot_weighting_scheme(fu_result60)
plot_weighting_scheme(fu_result48)
plot_weighting_scheme(fu_result36)
plot_weighting_scheme(fu_result24)

epu_result60<-fit_GarchMidas(epu,'hundredfold_return','epu',60)
epu_result48<-fit_GarchMidas(epu,'hundredfold_return','epu',48)
epu_result36<-fit_GarchMidas(epu,'hundredfold_return','epu',36)
epu_result24<-fit_GarchMidas(epu,'hundredfold_return','epu',24)
plot_weighting_scheme(epu_result60)
plot_weighting_scheme(epu_result48)
plot_weighting_scheme(epu_result36)
plot_weighting_scheme(epu_result24)

long_epu_result60<-fit_GarchMidas(long_epu,'return','logdiff_epu',60)
long_epu_result48<-fit_GarchMidas(long_epu,'return','logdiff_epu',48)
long_epu_result36<-fit_GarchMidas(long_epu,'return','logdiff_epu',36)
long_epu_result24<-fit_GarchMidas(long_epu,'return','logdiff_epu',24)
plot_weighting_scheme(long_epu_result60)
plot_weighting_scheme(long_epu_result48)
plot_weighting_scheme(long_epu_result36)
plot_weighting_scheme(long_epu_result24)
dev.off()

