# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_g <- function(omega, alpha, beta, returns, g0) {
    .Call('_GarchMidas_calculate_g', PACKAGE = 'GarchMidas', omega, alpha, beta, returns, g0)
}

sum_tau <- function(m, theta, phivar, covariate, K) {
    .Call('_GarchMidas_sum_tau', PACKAGE = 'GarchMidas', m, theta, phivar, covariate, K)
}

